---
title: Cross-clade thermosensory receptor guanlyate cyclase phylogenetic analysis 
output: html_notebook
---

```{r}
library(ape)
library(tidyverse)
library(ggtree)
library(ggexpand)
library(treeio)
library(magrittr)
library(rcartocolor)
library(Cairo)
```

## Import Treefile generated by IQ-Tree
```{r}
treefile <- file.choose()
tree <- read.iqtree(treefile)
tree_tbl <- as_tibble(tree)
```


## Code here to define sequence groups that will be colored differently (optional)
```{r}
Clade4nodes <- dplyr::filter(tree_tbl, grepl('Ce|DAF',label))
Str_nodes <- dplyr::filter(tree_tbl, grepl('SRAE|SSTP|Ss',label))
Clade5nodes <- dplyr::filter(tree_tbl, grepl('SRAE|Ss',label))
Ss_nodes <- dplyr::filter(tree_tbl, grepl('SSTP',label))
grp <- list (Elegans = Ce_nodes$node,
             Strongyloides = Str_nodes$node)
grp2 <- list (Elegans = Ce_nodes$node,
              Stercoralis = Ss_nodes$node,
              Ratti = Sr_nodes$node)
speciescolors <- c("Elegans" = "olivedrab", 
                   "Stercoralis" = "coral",
                   "Ratti" = "darkorchid")
```

## Plot a tree without colors
```{r}
p <- ggtree(tree, layout = "rectangular") +
    geom_tiplab(size = 2, hjust = -.05) + 
    #geom_cladelabel(node = 134, label = "AFD-specific rGCs", align = T, offset = 1.2,
     #               offset.text = .3, barsize = 1, angle = -4,
      #              hjust = 'center', fontsize = 3) +
    #geom_hilight(node=86, fill="grey", alpha=.5, extend = 3) +
    xlim(0, 6)
```

## Plot a tree with color groupings
```{r}
p2 <- groupOTU(p, grp, 'Species') + aes(color = Species) +
    scale_color_manual(values = speciescolors)
```

## Save plot as PDF
```{r}
ggsave(plot = p2,
       filename ="rGC_tree_rectangle.pdf",
       device = cairo_pdf,
       height = 2)

```
    

