---
title: "Cross-clade thermosensory receptor guanlyate cyclase phylogenetic analysis"
autho: "Ben Gregory and Astra Bryant"
date: "2/5/24"
output: html_notebook
---

```{r setup, eval=F, message=F, warning=F, results = "hide"}
setRepositories(ind = c(1,2,3,4,5))
libPath <- .libPaths()

if (!requireNamespace("treeio", quietly = TRUE)){
  if (!requireNamespace("pacman", quietly = TRUE))
      install.packages("pacman")
  library(pacman)
  pacman::p_load(ape, tidyverse,treeio,magrittr,rcartocolor,Cairo)
}

if (!requireNamespace("ggtree", quietly = TRUE)){
  if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
  library(BiocManager)
  remove.packages("patchwork", lib=libPath)
  devtools::install_github("thomasp85/patchwork")
  BiocManager::install("ggtree", ask = FALSE)
}

```

```{r, message=F, warning=F}
library(ape)
library(tidyverse)
library(ggtree)
library(treeio)
library(magrittr)
library(rcartocolor)
library(Cairo)
```

## Import Treefile generated by IQ-Tree
```{r import}
treefile <- file.choose()
tree <- read.iqtree(treefile)
tree_tbl <- as_tibble(tree)
```


## Code here to define sequence groups that will be colored differently (optional)
```{r colorGroups}
Clade5_nodes <- dplyr::filter(tree_tbl, grepl('Acey|ANCCAN|NAME|HCON|HPOL',label))
Clade4_nodes <- dplyr::filter(tree_tbl, grepl('SRAE|SSTP|Ss|Sr|L596|RSKR',label))
Clade3_nodes <- dplyr::filter(tree_tbl, grepl('EN70|DINM|AgR0|ALUE',label))

rGC_nodes <- dplyr::filter(tree_tbl, grepl('SRAE|SSTP|Ce|DAF',label))
Thermo_nodes <- dplyr::filter(tree_tbl, grepl('Ce-GCY-8|Ce-GCY-18|Ce-GCY-23|Ss|Sr|SSTP_0000846800|SSTP_0000775800|SSTP_0000354300|SRAE_0000007100|SRAE_2000430600|SRAE_X000209000',label))


grp <- list (Clade3 = Clade3_nodes$node,
             Clade4 = Clade4_nodes$node,
             Clade5 = Clade5_nodes$node,
             NonThermo_rGCs = rGC_nodes$node,
             CeStr_Thermo_rGCs = Thermo_nodes$node
             )

speciescolors <- c("NonThermo_rGCs" = "black", 
                   "CeStr_Thermo_rGCs" = "coral",
                   "Clade3" = "darkorchid",
                   "Clade4" = "royalblue",
                   "Clade5" = "palevioletred" 
                   )
```

## Plot a tree with color groupings
```{r plotTree, message=F, warning=F}
p <- ggtree(tree, branch.length='none', layout='rectangular') +
    geom_tiplab(size = 3, hjust = 0)  +
    geom_treescale(x=10, y=0)
#geom_cladelabel(node = 134, label = "AFD-specific rGCs", align = T, offset = 1,
               #offset.text = 1, barsize = 1, angle = -4,
              #hjust = 'center', fontsize = 3) +
#geom_hilight(node=86, fill="grey", alpha=.5, extend = 3) +
   

p2 <- groupOTU(p, grp, 'Species') + aes(color = Species) +
    scale_color_manual(values = speciescolors)
p2
```


## Save plot as PDF
```{r save, message=F, warning=F}
ggsave(plot = p2,
       filename = paste0(sub('\\..*$', '', basename(treefile)), "_Tree.pdf"),
       path = dirname(treefile),
       device = cairo_pdf,
       width = 12, 
       height = 10)

```
    

